### ISSUE TITLE
Calendar does not display

### ISSUE THREAD

**Issue by OpMaxis** [DasSauerkraut/calendar-weather#113]
Expected behavior: Calendar appears after joining into a game with About Time and Calendar/Weather modules enabled.

Actual behavior: Calendar does not appear. Using the GUI option to open the calendar has no effect, either; the events are firing in the console to instantiate the Calendar GUI object in both Foundry and Calendar/Weather, but nothing appears.

GIF example:
https://gfycat.com/sophisticatedornatefennecfox

Current versions: 
FoundryVTT: 0.6.2
AboutTime: 0.1.43
Calendar/Weather: 2.7.0

**Comment by OpMaxis** [comment]
Addition: This seems to be an isolated incident between my group, even between different accounts. Moving to a different test user on the same world, for example, had the calendar fully visible; another DM also had the calendar fully visible in the same world, but could not advance the psuedo-clock (which as I understand, is more managed by About Time)

**Comment by zoonza** [comment]
I'm having the same issue myself.

About Time v1.45
Calendar v2.70

**Comment by DasSauerkraut** [comment]
It's likely that the calendar is off screen. Type in the console CWCalendar.resetPos() and see how it do

**Comment by SamF111** [comment]
I have the same issue. I didn't have it on my W10 locally hosted version of the game, but do have it on my ubuntu droplet.

Writing CWCalendar.resetPos() doesn't apear to do anything.
I've copied the log from what happens if I try and toggle the display of the calendar.
`
CWCalendar.resetPos()
Promise {<pending>}
__proto__: Promise[[PromiseStatus]]: "pending"[[PromiseValue]]: undefined
62PseudoClock.js:14 about-time |  Real time handler fired
calendar.mjs:246 calendar-weather | Toggling calendar display.
foundry.js:3855 Foundry VTT | Rendering Calendar
ElapsedTime.js:519 about-time |  _save saving Tue Jul 28 2020 14:46:38 GMT+0100 (British Summer Time) 01:16:02
PseudoClock.js:14 about-time |  save times are  1595943998879 1595943919475 60000
PseudoClock.js:14 about-time |  _save saving Tue Jul 28 2020 14:46:38 GMT+0100 (British Summer Time) 50324289362
calendar.mjs:231 calendar-weather | Resetting Calendar Position
17PseudoClock.js:14 about-time |  Real time handler fired`

It's constantly doing things so I can verify that it works., in the time it took me to write this post the "17PseudoClock.js:14 about-time |  Real time handler fired" line has increased to.

`248PseudoClock.js:14 about-time |  Real time handler fired`

**Comment by SamF111** [comment]
I've tried this now with an ultra-wide monitor, and the calendar appears/dissappears as it should. It must have gotten stuck offscreen somehow.
