### ISSUE TITLE
[Request] Moon Cycles

### ISSUE THREAD

**Issue by Mimmitar** [DasSauerkraut/calendar-weather#81]
Another feature I am missing would be the ability to set custom/multiple moon cycles. This is especially important for PCs with hidden lycanthropy.

**Comment by DasSauerkraut** [comment]
Gonna get to work on this, just gonna use this issue to document my thoughts:
Can add multiple Moons
- Each Moon has Four values:
--- Cycle Length
--- Current Cycle Percent
--- Lunar Eclipse Chance
--- Solar Eclipse Chance

Each day, increment each moon's percent, if > 100, Full Moon; if < 0 New Moon. Roll Eclipse chance, if Lunar Eclipse, check if moon is full, if so, total lunar eclipse, otherwise partial lunar eclipse. Solar eclipse will cause light cycle affected scenes to dark for 30min at midday.
Display chat cards for lunar cycles at 0%, 25%, 50%, 75%, 100% cycle.
Full Moon doesn't turn off global illumination
New moon (if FXMaster is installed) causes an *even darker filter* TM to appear

**Comment by Mimmitar** [comment]
This is perfect, it even has things I had not considered. A blood moon for our werewolf pc...
