### ISSUE TITLE
[Bug] Season never changes

### ISSUE THREAD

**Issue by Craven112** [DasSauerkraut/calendar-weather#95]
I have 4 seasons set up, but it always stays autumn. I have set seasons up with correct dates.
The icon doesn't change, but it also outputs temperatures which are unreasonable (freezing during summer, for example).

Might be the same as issue #79, but that one only specifies the color.

Using:
Foundry 0.5.7 hotfix
Calendar weather 2.6.1 
About time 0.1.42

**Comment by silvative** [comment]
I think I'm having the same issue. Essentially, the module seems to think it's Autumn despite the dates- I've attached an image of the UI so you can see it should be summer. It's clearly using the Autumn colour and even updates if I change it. The temperatures also seem to be reflecting that as I'm getting very cold weather for August.

![Capture](https://user-images.githubusercontent.com/66365038/83630725-3586f000-a594-11ea-8187-63170611dca0.PNG)

I hope commenting here rather than creating a separate issue is correct- it seems to be the same bug.
